package com.example.demo.enums;

public enum DemoApiCodeEnum {
    API_ERROR_INEXISTENT_EMAIL,
    API_ERROR_EXISTENT_PRODUCT,
    API_ERROR_PRODUCT_DOESNT_EXIST,
    API_ERROR_COULDNT_CREATE_ORDER,
    API_ERROR_INEXISTENT_USER,
    API_ERROR_USER_ALREADY_EXISTS,
    API_ERROR_COULDNT_CREATE_USER,
    API_ERROR_COULDNT_DELETE_PRODUCT,
    API_ERROR_EXTERNAL_SERVICE
}
