server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

  # Configurações para cache com Redis
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

# Configuração customizada para API externa de validação de CPF
external:
  cpf-validator:
    url: https://api.exemplo.com

# Nivel de logs
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
